### ISSUE TITLE
Soundness issue

### ISSUE THREAD

**Issue by Freax13** [UnitedTraders/aeron-rs#13]
`CorrelatedMessageFlyweight` and `HeaderFlyweight` expose the `flyweight` field of type `Flyweight` which exposes the raw pointer `m_struct` which is dereferenced by `CorrelatedMessageFlyweight::client_id`, `CorrelatedMessageFlyweight::correlation_id`, `CorrelatedMessageFlyweight::set_client_id`, `CorrelatedMessageFlyweight::set_correlation_id`, `HeaderFlyweight::frame_length`, `HeaderFlyweight::version`, `HeaderFlyweight::flags`, `HeaderFlyweight::h_type`, `HeaderFlyweight::set_frame_length`, `HeaderFlyweight::set_version`, `HeaderFlyweight::set_flags` and `HeaderFlyweight::set_h_type`.

This is unsound because a user could modify `m_struct` in safe code and call one of those methods to cause UB.

**Comment by denisxor** [comment]
Fixed in version 0.1.5 - current master head.
